### ISSUE TITLE
[Feature Request] GetDateTime or GetDate / GetTime

### ISSUE THREAD

**Issue by evilalmus** [JPS-GER/ComfyUI_JPS-Nodes#2]
I installed your nodes mostly just for the GetDateTime node but many of the others are great as well. It is certainly convenient that the node has options for selecting the output format instead of forcing the user to remember which format of %Y %m %d %H %yyyy etc the node uses. 

It would be nice though if it allowed you to pick time strings without the date (%H%M%S). 
I'm not sure if this would be better as a seperate GetTime node or as additional options in the current node. I have workarounds in my workflow so this isn't a priority but if you think it is worth your time it would be appreciated. 
If this is out of scope or whatever just go ahead and close the request. ;)

**Comment by JPS-GER** [comment]
Something like that?

![grafik](https://github.com/JPS-GER/ComfyUI_JPS-Nodes/assets/142158778/5837c9cf-9543-4dd3-b376-56d2cccb47b2)

**Comment by evilalmus** [comment]
Yes! Exactly like that!

**Comment by JPS-GER** [comment]
Ok, will be in the next update -  just have to coordinate it with an upcoming release of my workflow, because the updated nodes (other parts, not the date-time node) would break the current workflow.

**Comment by JPS-GER** [comment]
New version is available now.
