### ISSUE TITLE
Dynamic prompts don't work when using prompt styler

### ISSUE THREAD

**Issue by photogsy** [JPS-GER/ComfyUI_JPS-Nodes#3]
Using SDXL Prompt Styler node, given the prompt {blue|red}, you get something that is blue AND red, instead of something that is EITHER blue or red.

https://github.com/JPS-GER/ComfyUI_JPS-Nodes/blob/5fa9f7243eb122c56eae40af7e00a87dc975c4c8/jps_nodes.py#L2232-L2234

Changing the return types to include ```dynamicPrompts``` as follows fixes this:
```
                "text_positive_g": ("STRING", {"default": "", "multiline": True, "dynamicPrompts": True}),
                "text_positive_l": ("STRING", {"default": "", "multiline": True, "dynamicPrompts": True}),
                "text_negative": ("STRING", {"default": "", "multiline": True, "dynamicPrompts": True}),
```

I'm not able to make a pull request so hopefully you can easily update this!

**Comment by JPS-GER** [comment]
Hello and thanks for the contribution. Can you please test, if it is working now?

**Comment by photogsy** [comment]
Hello, yes this is now working as expected. Many thanks!
